version: '2'

services:
    client:
        build:
            context: .
        volumes:
            - .:/usr/src/client:rw
            - /usr/src/client/node_modules
        ports:
            - '5579:5579'

volumes:
    db-data: {}
